In [1]:
import numpy as np

In [ ]:
a = np.array([1,2,3,4])

In [4]:
print(a)

[1 2 3 4]


In [6]:
#2D and 3D array
b = np.array([[1,2,3],[4,5,6]])

In [7]:
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
#1d is vector
#2d is matrix
#3d is tensor

In [10]:
np.array([1,2,0],dtype=bool)

array([ True,  True, False])

In [11]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [12]:
# np.arange
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [13]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
#reshape
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [27]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [18]:
np.arange(1,11).reshape(4,2)

ValueError: cannot reshape array of size 10 into shape (4,2)

In [ ]:
#np.ones and np.zeros are used to initialise arrays

In [20]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [23]:
np.zeros((2,1))

array([[0.],
       [0.]])

In [24]:
np.random.random((4,3))

array([[0.34260878, 0.76554588, 0.73886815],
       [0.19969122, 0.77189723, 0.81738463],
       [0.37004699, 0.83934027, 0.91154636],
       [0.73232166, 0.94936034, 0.59122529]])

In [26]:
# np.linspace
#np.linspace(lrange,Urange, No. of items)
#equally spaced value
np.linspace(-10,10,10,dtype=int)

array([-10,  -8,  -6,  -4,  -2,   1,   3,   5,   7,  10])

In [28]:
# np.identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [48]:
a1 = np.arange(10, dtype=np.int32) #bydefault int64 is used which is 4bits
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [30]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [31]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [34]:
#ndim is for dimension 
a2.ndim

2

In [40]:
#shape
print(a3.shape)
a3
# first 2 tells number of 2d arrays and second and third two will tell us the dimension of those arrays

(2, 2, 2)


array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [36]:
a2.shape

(3, 4)

In [37]:
a1.shape

(10,)

In [43]:
# size tells the no. elements

a2.size

12

In [49]:
#itemsize tells the memomry occupied
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [51]:
# dtype tells us the data type of the array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


In [54]:
# astype is used to change the datatype
#as seen in cell 53 is does not change the original but actually just create the copy
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

In [53]:
a3.dtype

dtype('int64')

In [56]:
#ARRAY OPERATIONS
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [59]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [60]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [61]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [62]:
a1**2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [64]:
# all operation will work like +-/* // ** everything

In [66]:
a1 > 5  #check whether every element is greater than 5 or not

array([[False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [67]:
a1 * 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [68]:
a1 + a2

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [69]:
#There are many function in numpy so you can just google the function and use them

In [72]:
print(np.max(a1))
print(np.min(a1))
print(np.prod(a1))  #product of all elements in the matrix

11
0
0


In [73]:
print(np.prod(a2))

647647525324800


In [75]:
np.max(a1, axis=0) #max in every col
# 0 is col and 1 is row

array([ 8,  9, 10, 11])

In [76]:
np.max(a1,axis=1)

array([ 3,  7, 11])

In [77]:
np.prod(a1, axis = 1)

array([   0,  840, 7920])

In [78]:
print(np.mean(a1))
print(np.std(a1))
print(np.var(a1))
print(np.sin(a1))

5.5
3.452052529534663
11.916666666666666
[[ 0.          0.84147098  0.90929743  0.14112001]
 [-0.7568025  -0.95892427 -0.2794155   0.6569866 ]
 [ 0.98935825  0.41211849 -0.54402111 -0.99999021]]


In [83]:
# dot product
np.dot(a1,a2) #not possible due to different shape mxn nxk type

ValueError: shapes (3,4) and (3,4) not aligned: 4 (dim 1) != 3 (dim 0)

In [85]:
a3 = np.arange(16).reshape((4,4))

In [86]:
np.dot(a2,a3)

array([[344, 398, 452, 506],
       [440, 510, 580, 650],
       [536, 622, 708, 794]])

In [89]:
print(np.exp(a1))
print(np.log(a1))
print(np.ceil(a1*100))

[[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03]
 [2.98095799e+03 8.10308393e+03 2.20264658e+04 5.98741417e+04]]
[[      -inf 0.         0.69314718 1.09861229]
 [1.38629436 1.60943791 1.79175947 1.94591015]
 [2.07944154 2.19722458 2.30258509 2.39789527]]
[[   0  100  200  300]
 [ 400  500  600  700]
 [ 800  900 1000 1100]]


C:\Users\Akshat Sonkar\AppData\Local\Temp\ipykernel_1308\589165112.py:2: RuntimeWarning: divide by zero encountered in log
  print(np.log(a1))


In [94]:
#IMPORTANT
print(np.random.random((2,3))) #gives random number
print(np.random.random((2,3))*100) #multiplies the random number by 100
print(np.round(np.random.random((2,3))*100)) #round of the number to nearest int

[[0.33821459 0.88376971 0.15906892]
 [0.89102035 0.58334487 0.29122941]]
[[79.48097327 28.94459437 51.6410013 ]
 [38.83081362 16.70802831  5.54775223]]
[[83. 95. 85.]
 [34. 61. 37.]]


In [96]:
#INDEXING AND SLICING
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [97]:
a1[1,0]

np.int64(4)

In [98]:
a1[1]

array([4, 5, 6, 7])

In [99]:
a1[-1]

array([ 8,  9, 10, 11])

In [101]:
a1[-1,3] #negative indexing for row and normal for col

np.int64(11)

In [103]:
a3 = np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [104]:
a3[1,0,1]

np.int64(5)

In [107]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [110]:
a1[0:1] # python me last wale ko ignore kar diya jata hai

array([[0, 1, 2, 3]])

In [111]:
a1[1,:]

array([4, 5, 6, 7])

In [113]:
a1[:,1]

array([1, 5, 9])

In [116]:
a1[1:3,2:4] #row slice 1 to 2 and col slice 2 to 3 

array([[ 6,  7],
       [10, 11]])

In [122]:
a1[::2 ,::3]
#commas are for separating rows, column, matrix
#first colon is to give slice and second is to tell the gap
#when writing see how many rows you want in this case 0 and 2 ie 2 gap for rows and 3 gap for col
#array[matrixstart:,matrixend:gap,rowstart:rowend:gap,colstart:colend:gap]

array([[ 0,  3],
       [ 8, 11]])

In [123]:
a1[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [191]:
#Fancy Indexing
a1[:,[0,2,3]]  #passes a list and tells which rows or cols we need 

array([[ 0,  2,  3],
       [ 4,  6,  7],
       [ 8, 10, 11]])

In [194]:
# Boolean Indexing
a3 = np.random.randint(1,100,24).reshape(6,4)
#in this randint is used to get 24 random numbers in range of 1 to 100
#On my system randint() is returning int32 by default

a3

array([[98, 96, 87, 66],
       [96, 34, 74,  5],
       [59, 89, 80, 24],
       [42, 70,  1, 77],
       [87, 82, 99, 47],
       [47, 91, 35,  1]], dtype=int32)

In [196]:
a3>50
#This array we got is called boolean array

array([[ True,  True,  True,  True],
       [ True, False,  True, False],
       [ True,  True,  True, False],
       [False,  True, False,  True],
       [ True,  True,  True, False],
       [False,  True, False, False]])

In [197]:
a3[a3>50] #This is boolean indexing where we get array based on conditions

array([98, 96, 87, 66, 96, 74, 59, 89, 80, 70, 77, 87, 82, 99, 91],
      dtype=int32)

In [124]:
#LOOPS
a1 = np.arange(12)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(18).reshape(3,2,3)

In [125]:
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [126]:
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [127]:
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[12 13 14]
 [15 16 17]]


In [129]:
#This convert multidimensional array to 1d and then prints it
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17


In [130]:
#RESHAPING

In [132]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [134]:
# Transpose
np.transpose(a2) #one way


array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [139]:
a2.T #shortcut or smaller way

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [140]:
# ravel converts multidimensional array into 1d
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [143]:
#STACKING
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [144]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [147]:
#Horizontal Stacking
np.hstack((a1,a2)) #inside a tupple ie 2 brackets

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [148]:
# Vertical Stacking
np.vstack((a1,a2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [150]:
a3 = np.arange(16).reshape(4,4)

In [153]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [152]:
a3

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [151]:
np.vstack((a1,a4))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
np.hstack((a1,a3))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 3 and the array at index 1 has size 4

In [163]:
#SPLITTING
#Horizontal splliting means that the matrix will be cut in line perpendicular to horizontal vice versa

In [164]:
#Horizontal Splitting
print(a1)
np.hsplit(a1,2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [165]:
np.hsplit(a1,4)

[array([[0],
        [4],
        [8]]),
 array([[1],
        [5],
        [9]]),
 array([[ 2],
        [ 6],
        [10]]),
 array([[ 3],
        [ 7],
        [11]])]

In [167]:
#Vertical Splliting
np.vsplit(a1,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [168]:
#NUMPY ARRAY VS PYTHON LIST
#numpy aaya cause python was slow
#numpy is just C wrapped python

In [175]:
#Speed

#list
a = [i for i in range(10000000)]   #[0, 1, 2, 3, 4, 5, ..., 9999997, 9999998, 9999999]
b = [i for i in range(10000000,20000000)]   #[10000000, 10000001, ...,  19999998, 19999999]

c = []

In [171]:
 #this is a module which lets us deal with real time 
import time

In [172]:
start = time.time() #this is like a stopwatch which saves the time at this point in start variable

for i in range(len(a)):
  c.append(a[i] + b[i])
print(time.time()-start)  #this subtracts the start time from current time

0.9769461154937744


In [173]:
# numpy
a = np.arange(10000000)
b = np.arange(10000000,20000000)

start = time.time()
c = a + b
print(time.time()-start)

0.02992415428161621


In [174]:
0.9769461154937744/0.02992415428161621

32.647409390411994

In [176]:
#32 times faster in this case
#reason for this is numpy uses C type array ie its size is fixed, stores homogeneous datatypes and it stores data in memory and not its address like in python list

In [ ]:
#Memory
import sys

In [183]:
a = [i for i in range(10000000)]
print("For list size in bytes : " , sys.getsizeof(a))
a = np.arange(10000000)
print("For numpy array size in bytes : " ,sys.getsizeof(a))

For list size in bytes :  89095160
For numpy array size in bytes :  80000112


In [186]:
#also we can choose the datatype in numpy array as well which is not possible in list
a = np.arange(10000000,dtype=np.int8)
print("For numpy array of int8 bit type size in bytes : " ,sys.getsizeof(a))

#note -> we int8 means -128 to 127 so after 127 the value wraps ie 128 will be stored as -128

For numpy array of int8 bit type size in bytes :  10000112


In [187]:
#Convenience, see how easy adding the elements in list were 

In [198]:
#BROADCASTING

#The term broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
#The smaller array is “broadcast” across the larger array so that they have compatible shapes.
#In simple words it is how the numpy broadcasts that is enlarges the smaller array so that the arithmetic operation is possible. 

In [199]:
# diff shape
a = np.arange(6).reshape(2,3)
b = np.arange(3).reshape(1,3)

print(a)
print(b)

print(a+b)

[[0 1 2]
 [3 4 5]]
[[0 1 2]]
[[0 2 4]
 [3 5 7]]


In [204]:
#Broadcasting rules
#1) Make a number of dimensions same Eg-> (3,3):(3) -> (3,3):(1,3)
#2) Make the value/size of dimension same Eg-> (3,3):(1,3) -> (3,3):(3,3)
# inrule no.1 1 is added to the front
#in rule no.2 1 is stretched until it is same as the needed size and if there isno one then cannot be broadcasted

![Broadcasting Image](https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png)

In [205]:
a = np.arange(12).reshape(3,4)
b = np.arange(12).reshape(4,3)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


ValueError: operands could not be broadcast together with shapes (3,4) (4,3) 

In [207]:
#IMPORTANT
a = np.arange(16).reshape(4,4)
b = np.arange(4).reshape(2,2)

print(a)
print(b)

print(a+b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1]
 [2 3]]


ValueError: operands could not be broadcast together with shapes (4,4) (2,2) 

In [225]:
#NUMPY MATHEMATICAL FORMULAS
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [226]:
np.sum(a)

np.int64(66)

In [227]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001],
       [-0.7568025 , -0.95892427, -0.2794155 ,  0.6569866 ],
       [ 0.98935825,  0.41211849, -0.54402111, -0.99999021]])

In [228]:
# Sigmoid(IMPORTANT)
def sigmoid(array):
  return 1/(1 + np.exp(-(array)))

    # 1 / 1 + e^-x

sigmoid(a)

array([[0.5       , 0.73105858, 0.88079708, 0.95257413],
       [0.98201379, 0.99330715, 0.99752738, 0.99908895],
       [0.99966465, 0.99987661, 0.9999546 , 0.9999833 ]])

In [230]:
# Mean Squared Error

actual = np.random.randint(1,50,25)
predicted = np.random.randint(1,50,25)

In [231]:
actual

array([49,  6, 45, 48, 37, 22, 36, 19, 15, 15, 40, 27, 39, 41, 31, 22, 16,
       41, 42,  4, 26, 13, 47,  9, 43], dtype=int32)

In [232]:
predicted

array([45, 49, 39, 47, 15, 20, 14, 33, 35, 33, 15, 19, 48, 44, 25, 38, 20,
       12,  8, 40,  9, 47, 33, 21, 28], dtype=int32)

In [234]:
def mse(actual,predicted):
  return np.mean((actual - predicted)**2)

#formula was (x -xnot)^2/N

mse(actual,predicted)

np.float64(407.36)

In [236]:
#WORKING WITH MISSING VALUES

a = np.array([1,2,3,4,np.nan,6])
a
#nan and NONE are not same

array([ 1.,  2.,  3.,  4., nan,  6.])

In [239]:
#to remove all missing value, we do boolean indexing ie ask are you missing value if No then return false and we do complement so it makes it true and written in array while for nan its true and complements makes it false so not written in array
a[~np.isnan(a)]

array([1., 2., 3., 4., 6.])

In [241]:
#IAMLEAVING MATPLOTLIB AND MESH GRIDS OF THIS LECTURE 2 FOR LATER

In [242]:
#NUMPY TRICKS

In [243]:
a = np.random.randint(1,100,15)
a

array([98, 32, 97, 62, 75, 33, 22, 49, 30, 91,  3,  1, 15, 41, 31],
      dtype=int32)

In [244]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[42, 51, 98, 55],
       [ 4, 68, 49,  4],
       [75, 35, 46, 54],
       [ 6, 71, 23,  2],
       [42, 62, 45, 81],
       [52, 96, 53, 87]], dtype=int32)

In [260]:
#sorted gives us list but np.sort will give us the array itself and not list

#numpy.sort(a, axis=-1, kind=None, order=None, *, stable=None)
    #kind{‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, optional
    #orderstr or list of str, optional
    #stablebool, optional

In [253]:
np.sort(a)[::] #ascending

array([ 1,  3, 15, 22, 30, 31, 32, 33, 41, 49, 62, 75, 91, 97, 98],
      dtype=int32)

In [254]:
np.sort(a)  #ascending

array([ 1,  3, 15, 22, 30, 31, 32, 33, 41, 49, 62, 75, 91, 97, 98],
      dtype=int32)

In [255]:
np.sort(a)[::-1]  #descending

array([98, 97, 91, 75, 62, 49, 41, 33, 32, 31, 30, 22, 15,  3,  1],
      dtype=int32)

In [262]:
np.sort(b) #bydefault rowwise sorting

array([[42, 51, 55, 98],
       [ 4,  4, 49, 68],
       [35, 46, 54, 75],
       [ 2,  6, 23, 71],
       [42, 45, 62, 81],
       [52, 53, 87, 96]], dtype=int32)

In [256]:
np.sort(b,axis=0)  #column wise sort

array([[ 4, 35, 23,  2],
       [ 6, 51, 45,  4],
       [42, 62, 46, 54],
       [42, 68, 49, 55],
       [52, 71, 53, 81],
       [75, 96, 98, 87]], dtype=int32)

In [257]:
np.sort(b,axis=1)  #row wise sort

array([[42, 51, 55, 98],
       [ 4,  4, 49, 68],
       [35, 46, 54, 75],
       [ 2,  6, 23, 71],
       [42, 45, 62, 81],
       [52, 53, 87, 96]], dtype=int32)

In [258]:
a

array([98, 32, 97, 62, 75, 33, 22, 49, 30, 91,  3,  1, 15, 41, 31],
      dtype=int32)

In [259]:
np.append(a,200) #insert at last

array([ 98,  32,  97,  62,  75,  33,  22,  49,  30,  91,   3,   1,  15,
        41,  31, 200])

In [263]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[42., 51., 98., 55.,  1.],
       [ 4., 68., 49.,  4.,  1.],
       [75., 35., 46., 54.,  1.],
       [ 6., 71., 23.,  2.,  1.],
       [42., 62., 45., 81.,  1.],
       [52., 96., 53., 87.,  1.]])

In [270]:
#np.concatenate
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [266]:
np.concatenate((c,d))  #works like a tupple ie two brackets

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [267]:
np.concatenate((c,d),axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [268]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [271]:
#np.unique
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
np.unique(e)

array([1, 2, 3, 4, 5, 6])

In [274]:
#np.expand_dims
b

array([[42, 51, 98, 55],
       [ 4, 68, 49,  4],
       [75, 35, 46, 54],
       [ 6, 71, 23,  2],
       [42, 62, 45, 81],
       [52, 96, 53, 87]], dtype=int32)

In [275]:
b.shape

(6, 4)

In [276]:
a

array([98, 32, 97, 62, 75, 33, 22, 49, 30, 91,  3,  1, 15, 41, 31],
      dtype=int32)

In [277]:
a.shape

(15,)

In [279]:
np.expand_dims(a,axis=0) #if you notice there is an extra square brackets which says that it is now 2d array

array([[98, 32, 97, 62, 75, 33, 22, 49, 30, 91,  3,  1, 15, 41, 31]],
      dtype=int32)

In [280]:
np.expand_dims(a,axis=0).shape

(1, 15)

In [281]:
np.expand_dims(a,axis=1).shape

(15, 1)

In [283]:
np.expand_dims(a,axis=1)

array([[98],
       [32],
       [97],
       [62],
       [75],
       [33],
       [22],
       [49],
       [30],
       [91],
       [ 3],
       [ 1],
       [15],
       [41],
       [31]], dtype=int32)

In [284]:
np.expand_dims(b,axis=0)

array([[[42, 51, 98, 55],
        [ 4, 68, 49,  4],
        [75, 35, 46, 54],
        [ 6, 71, 23,  2],
        [42, 62, 45, 81],
        [52, 96, 53, 87]]], dtype=int32)

In [285]:
np.expand_dims(b,axis=0).shape

(1, 6, 4)

In [289]:
np.expand_dims(b,axis=0)

array([[[42, 51, 98, 55],
        [ 4, 68, 49,  4],
        [75, 35, 46, 54],
        [ 6, 71, 23,  2],
        [42, 62, 45, 81],
        [52, 96, 53, 87]]], dtype=int32)

In [286]:
np.expand_dims(b,axis=1).shape

(6, 1, 4)

In [290]:
np.expand_dims(b,axis=1)

array([[[42, 51, 98, 55]],

       [[ 4, 68, 49,  4]],

       [[75, 35, 46, 54]],

       [[ 6, 71, 23,  2]],

       [[42, 62, 45, 81]],

       [[52, 96, 53, 87]]], dtype=int32)

In [287]:
np.expand_dims(b,axis=2).shape

(6, 4, 1)

In [288]:
np.expand_dims(b,axis=2)

array([[[42],
        [51],
        [98],
        [55]],

       [[ 4],
        [68],
        [49],
        [ 4]],

       [[75],
        [35],
        [46],
        [54]],

       [[ 6],
        [71],
        [23],
        [ 2]],

       [[42],
        [62],
        [45],
        [81]],

       [[52],
        [96],
        [53],
        [87]]], dtype=int32)

In [291]:
#np.where find all INDICES with value greater than 50
print(a)
np.where(a>50)

[98 32 97 62 75 33 22 49 30 91  3  1 15 41 31]


(array([0, 2, 3, 4, 9]),)

In [293]:
# replace all values > 50 with 0
np.where(a>50,0,a)

array([ 0, 32,  0,  0,  0, 33, 22, 49, 30,  0,  3,  1, 15, 41, 31],
      dtype=int32)

In [296]:
#np.argmax returns indices of the max element of the array in a particular axis
print(b)
np.argmax(b,axis=1)

[[42 51 98 55]
 [ 4 68 49  4]
 [75 35 46 54]
 [ 6 71 23  2]
 [42 62 45 81]
 [52 96 53 87]]


array([2, 1, 0, 1, 3, 1])

In [297]:
print(a)
np.argmax(a)

[98 32 97 62 75 33 22 49 30 91  3  1 15 41 31]


np.int64(0)

In [298]:
# np.argmin
np.argmin(a)

np.int64(11)

In [299]:
#1np.cumsum is used to calculatae cumulative sum of array elements over a given axis
print(a)
np.cumsum(a)

[98 32 97 62 75 33 22 49 30 91  3  1 15 41 31]


array([ 98, 130, 227, 289, 364, 397, 419, 468, 498, 589, 592, 593, 608,
       649, 680])

In [300]:
print(b)
np.cumsum(b,axis=1)

[[42 51 98 55]
 [ 4 68 49  4]
 [75 35 46 54]
 [ 6 71 23  2]
 [42 62 45 81]
 [52 96 53 87]]


array([[ 42,  93, 191, 246],
       [  4,  72, 121, 125],
       [ 75, 110, 156, 210],
       [  6,  77, 100, 102],
       [ 42, 104, 149, 230],
       [ 52, 148, 201, 288]])

In [301]:
# np.cumprod
np.cumprod(a)

array([                  98,                 3136,               304192,
                   18859904,           1414492800,          46678262400,
              1026921772800,       50319166867200,     1509575006016000,
         137371325547456000,   412113976642368000,   412113976642368000,
        6181709649635520000, -4804321396877402624, -1360010713523068416])

In [302]:
#np.percentile
np.percentile(a,50)

np.float64(33.0)

In [303]:
#np.median
np.median(a)

np.float64(33.0)

In [304]:
#np.histogram
np.histogram(a,bins=[0,20,40,60,80,100]) #it means frequency in 0-20, 20-40, 40-60 .... 80-100

(array([3, 5, 2, 2, 3]), array([  0,  20,  40,  60,  80, 100]))

In [305]:
#np.corrcoeff aka correlation cofficient
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

In [306]:
#note -> we got a matrix because it finds correlation between itself and other
#                Salary    |     Experience
# Salary           1                0.25 
# Experience      0.25               1

In [307]:
#np.isin
items = [10,20,30,40,50,60,70,80,90,100]

a[np.isin(a,items)]

array([30], dtype=int32)

In [308]:
#np.flip reverses the order of array elements along the specified axis
print(a)
np.flip(a)

[98 32 97 62 75 33 22 49 30 91  3  1 15 41 31]


array([31, 41, 15,  1,  3, 91, 30, 49, 22, 33, 75, 62, 97, 32, 98],
      dtype=int32)

In [312]:
#np.put replaces specific elements of an array with given values of p_array
print(a)
np.put(a,[0,1],[110,530])

[110 530  97  62  75  33  22  49  30  91   3   1  15  41  31]


In [314]:
#np.delete returns a new array with the deletion of sub-arrays along with the mentioned axis.
print(a)
np.delete(a,[0,2,4])

[110 530  97  62  75  33  22  49  30  91   3   1  15  41  31]


array([530,  62,  33,  22,  49,  30,  91,   3,   1,  15,  41,  31],
      dtype=int32)

In [325]:
#SET FUNCTIONS
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [316]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [317]:
np.intersect1d(m,n)

array([3, 4, 5])

In [318]:
np.setdiff1d(n,m)

array([6, 7])

In [319]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [323]:
#m[np.in1d(m,1)] this works as well but is old
m[np.isin(m,[1,6,2])]  #just checks whether function is there or not and returns if it is there

array([1, 2])

In [327]:
#np.clip
print(a)
np.clip(a,a_min=25,a_max=75)

[110 530  97  62  75  33  22  49  30  91   3   1  15  41  31]


array([75, 75, 75, 62, 75, 33, 25, 49, 30, 75, 25, 25, 25, 41, 31],
      dtype=int32)

In [331]:
#np.swapaxes
print(b)
np.swapaxes(b,0,1)

[[42 51 98 55]
 [ 4 68 49  4]
 [75 35 46 54]
 [ 6 71 23  2]
 [42 62 45 81]
 [52 96 53 87]]


array([[42,  4, 75,  6, 42, 52],
       [51, 68, 35, 71, 62, 96],
       [98, 49, 46, 23, 45, 53],
       [55,  4, 54,  2, 81, 87]], dtype=int32)

In [335]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [339]:
np.swapaxes(c,0,2)

array([[[ 0, 12],
        [ 4, 16],
        [ 8, 20]],

       [[ 1, 13],
        [ 5, 17],
        [ 9, 21]],

       [[ 2, 14],
        [ 6, 18],
        [10, 22]],

       [[ 3, 15],
        [ 7, 19],
        [11, 23]]])

In [341]:
#np.count_nonzero
k = [1,2,4,0,3,0,0,0,3,0,1]
np.count_nonzero(k)

np.int64(6)